CREATE DATABASE CrashTable;
USE CrashTable;
#DDL for CrashTable (adjusting types for typical MySQL/PostgreSQL environments)
CREATE TABLE CrashTable (
    CRASH_RECORD_ID TEXT,
    CRASH_DATE TEXT,
    POSTED_SPEED_LIMIT BIGINT,
    WEATHER_CONDITION TEXT,
    LIGHTING_CONDITION TEXT,
    FIRST_CRASH_TYPE TEXT,
    TRAFFICWAY_TYPE TEXT,
    PRIM_CONTRIBUTORY_CAUSE TEXT,
    SEC_CONTRIBUTORY_CAUSE TEXT,
    INJURIES_FATAL DOUBLE,
    INJURIES_INCAPACITATING DOUBLE,
    INJURIES_NON_INCAPACITATING DOUBLE,
    INJURIES_TOTAL DOUBLE,
    CRASH_HOUR BIGINT,
    CRASH_DAY_OF_WEEK BIGINT,
    CRASH_MONTH BIGINT,
    BEAT_OF_OCCURRENCE DOUBLE,
    STREET_NAME TEXT,
    LATITUDE DOUBLE,-- Note: Column name needs quotation marks due to special characters
    DATE_POLICE_NOTIFIED TEXT,
    year TEXT
);
#'''DATA EXPLORING'''
SELECT PRIM_CONTRIBUTORY_CAUSE, COUNT(*) AS crash_count From crashtable 
GROUP BY PRIM_CONTRIBUTORY_CAUSE ORDER BY crash_count DESC LIMIT 5;
#""THIS YEAR DATA'''
SELECT year, COUNT(*) AS total_crashes From CrashTable GROUP BY year ORDER BY year ASC;

#WEATHER CONDITION#
select weather_condition, FIRST_CRASH_TYPE, COUNT(*) AS total_crashes FROM CrashTable 
GROUP BY WEATHER_CONDITION, FIRST_CRASH_TYPE ORDER BY total_crashes DESC LIMIT 5;

#INJURIES CONDITION#
SELECT STREET_NAME, SUM(INJURIES_TOTAL)AS total_injuries FROM CrashTable GROUP BY STREET_NAME 
ORDER BY total_injuries DESC LIMIT 10;
